# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.16

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - add_ssh_keys:
          fingerprints:
              - "23:00:a5:97:cc:e9:9e:5f:03:09:e9:ab:bc:57:08:2c"


      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: jest test

      # Deploy
      - run:
            name: Deploy over SSH
            command: |
              ssh circleci@blog.killinsun.com -p 22 "cd /usr/local/share/docker-compose/teclub-slackbot/src/; git pull origin master; cd ../; docker-compose restart"
